name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: cp .env.sample .env
      - run: npm run lint

      - run: npm run test

